# Site
name: "NinggraIngga"
title: "NinggraIngga"
description: "Discover the world's Hidden Vacation Gems"
logo: '/favicon.ico'
favicon: '/favicon.ico'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
    name: Sri Maulina Rahayu
    display_name: Sri Maulina Rahayu
    avatar: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh2mc5gN0ijT7cf30O08auQ1ddH7hXpj0_U7zm3yriuNm72Xl7uxiicjmrHoK2Nn-AvaLKDaZ2KYfMo8_Qd7IDoBE8ut3JGbS21-5cblmhkDF3Vv88MaBg9qKYI_Oijo-IpX8kQhiRNxlL2iOVV2mRXRn-w6lI8rUoUakrm1SS0X2B4It2ilGFik8VJQ7wh/s1600/20240922_200528.png'
    email: ninggraingga@gmail.com
    web: /aboutme
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 4
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
